# library name
lib.name = externals.howto.foaAmbiPan~

# input source file (class name == source file basename)
class.sources = foaAmbiPan~.c

# all extra files to be included in binary distribution of the library
datafiles =

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
PDLIBBUILDER_DIR=../pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
